# Freight marine ship attributes

# Draught limit for marine modes in each Finnish port
port_draught_limit = {
    "container_ship": {
        "FIHEL": 12,
        "FISKV": 12,
        "FIHNK": 12,
        "FIINK": 12,
        "FIPOR": 12,
        "FIRAU": 12,
        "FITKU": 12,
        "FIPAR": 5,
        "FIUKI": 8,
        "FIHMN": 15,
        "FIKOK": 12,
        "FIKEM": 12,
        "FIKAS": 8,
        "FIVAA": 8,
        "FIOUL": 8,
        "FIRAA": 8,
        "FIKJO": 8,
        "FILPP": 5,
        "FIJOE": 5,
        "FISII": 5,
        "FIVRK": 5
    },
    "general_cargo": {
        "FIHEL": 12,
        "FISKV": 12,
        "FIHNK": 12,
        "FIINK": 12,
        "FIPOR": 15,
        "FIRAU": 12,
        "FITKU": 12,
        "FIPAR": 5,
        "FIUKI": 8,
        "FIHMN": 15,
        "FIKOK": 12,
        "FIKEM": 12,
        "FIKAS": 8,
        "FIVAA": 8,
        "FIOUL": 8,
        "FIRAA": 8,
        "FIKJO": 8,
        "FILPP": 5,
        "FIJOE": 5,
        "FISII": 5,
        "FIVRK": 5
    },
    "lng_carrier": {
        "FIHEL": 12,
        "FISKV": 12,
        "FIHNK": 12,
        "FIINK": 12,
        "FIPOR": 12,
        "FIRAU": 12,
        "FITKU": 12,
        "FIPAR": 5,
        "FIUKI": 8,
        "FIHMN": 12,
        "FIKOK": 12,
        "FIKEM": 12,
        "FIKAS": 8,
        "FIVAA": 8,
        "FIOUL": 8,
        "FIRAA": 8,
        "FIKJO": 8,
        "FILPP": 5,
        "FIJOE": 5,
        "FISII": 5,
        "FIVRK": 5
    },
    "oil_tanker": {
        "FIHEL": 12,
        "FISKV": 15,
        "FIHNK": 12,
        "FIINK": 12,
        "FIPOR": 12,
        "FIRAU": 12,
        "FITKU": 15,
        "FIPAR": 5,
        "FIUKI": 8,
        "FIHMN": 8,
        "FIKOK": 12,
        "FIKEM": 12,
        "FIKAS": 8,
        "FIVAA": 8,
        "FIOUL": 8,
        "FIRAA": 8,
        "FIKJO": 8,
        "FILPP": 5,
        "FIJOE": 5,
        "FISII": 5,
        "FIVRK": 5
    },
    "product_tanker": {
        "FIHEL": 12,
        "FISKV": 15,
        "FIHNK": 12,
        "FIINK": 12,
        "FIPOR": 12,
        "FIRAU": 12,
        "FITKU": 15,
        "FIPAR": 5,
        "FIUKI": 8,
        "FIHMN": 12,
        "FIKOK": 12,
        "FIKEM": 12,
        "FIKAS": 8,
        "FIVAA": 8,
        "FIOUL": 8,
        "FIRAA": 8,
        "FIKJO": 8,
        "FILPP": 5,
        "FIJOE": 5,
        "FISII": 5,
        "FIVRK": 5
    },
    "roro_vessel": {
        "FIHEL": 8,
        "FISKV": 8,
        "FIHNK": 8,
        "FIINK": 8,
        "FIPOR": 8,
        "FIRAU": 8,
        "FITKU": 8,
        "FIPAR": 5,
        "FIUKI": 8,
        "FIHMN": 8,
        "FIKOK": 8,
        "FIKEM": 8,
        "FIKAS": 8,
        "FIVAA": 8,
        "FIOUL": 8,
        "FIRAA": 8,
        "FIKJO": 8,
        "FILPP": 5,
        "FIJOE": 5,
        "FISII": 5,
        "FIVRK": 5
    }
}

# Marine mode draught speed relation in km/h format
ship_draught_speed = {
    "container_ship": {
        4: 20.1,
        5: 20.1,
        8: 24.0,
        12: 26.0,
        15: 27.6
    },
    "oil_tanker": {
        4: 20.1,
        5: 20.1,
        8: 20.6,
        12: 21.3,
        15: 21.8
    },
    "product_tanker": {
        4: 20.1,
        5: 20.1,
        8: 20.6,
        12: 21.3,
        15: 21.8
    },
    "lng_carrier": {
        4: 20.1,
        5: 20.1,
        8: 20.6,
        12: 21.3,
        15: 21.8
    },
    "general_cargo": {
        4: 16.9,
        5: 17.6,
        8: 20.1,
        12: 20.6,
        15: 20.9
    },
    "roro_vessel": {
        4: 22.7,
        5: 24.1,
        8: 29.4,
        12: 29.4,
        15: 29.4
    }
}
